services:
  pg-databases:
    image: postgres:15
    environment:
      - POSTGRES_USER=root 
      - POSTGRES_PASSWORD=root 
      - POSTGRES_DB=ny_taxi 
    volumes:
      - "./ny_taxi:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - airflow


networks:
  airflow:
    external:
      name: airflow_default

  # pgadmin4:
  #   image: dpage/pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.com 
  #     - PGADMIN_DEFAULT_PASSWORD=root 
  #   ports:
  #     - "8080:80"
